### ISSUE TITLE
Buttplug Unity no longer working in Unity < 2021

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-unity#15]
Unity 2019 throws DLL errors because of missing JSON and Threading DLLs.

**Comment by qdot** [comment]
Confirmed that this was missing a whole slew of DLLs. Fixed locally but I'm trying to get the new version of the C# Client API done, so I'll resolve this out once that's released and I can bring it over here (hopefully in the next week or so)

**Comment by McArdellje** [comment]
How did you fix this locally?

**Comment by qdot** [comment]
This was with the new build I'm working on, hopefully out this week.

**Comment by qdot** [comment]
@J-E-Mc If you'd like, you can check out the dev branch, I've got the updated library and dependencies there, things seem to work for me now. I should have a release out this week.

**Comment by qlee01** [comment]
Would be great to get a release! Currently it's not working in builds due to missing dlls in 2021.3.28 LTS, and it's also not possible to directly install it from git

**Comment by qdot** [comment]
Fixed in v3.0.1. Then again in v3.0.2 an hour later. But should really be fixed now.

Removed the need for one of the DLLs, and moved the JSON dependency to use the unity distributed Newtonsoft version.

Tested on a game using 2020.3.27f1, as well as in a clean 6 project, got it working on both, going to assume we're compatible from 2019.4+ to 6

Closing.
