### ISSUE TITLE
Possible bug / memory leak during scanning for devices in new version  

### ISSUE THREAD

**Issue by qlee01** [buttplugio/buttplug-unity#18]
Hi, I see issues with latest version (using the version from dev branch, as version on master breaks builds):
The process client.StartScanningAsync() does not seem to ever stop, and produces lots of memory heap, leading to very fast increasing memory consumption.

**Comment by qdot** [comment]
Oh damnit, I fixed this in the main library and forgot to port it over.

**Comment by qdot** [comment]
Ok, fixed now, pull the dev branch again and let me know if it works for you. I'll close this once I get confirmation.

**Comment by qlee01** [comment]
> Ok, fixed now, pull the dev branch again and let me know if it works for you. I'll close this once I get confirmation.

@qdot Wow, that was fast :) Thanks, this fixes the issue for me! No more memory leak.
